# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: immvis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='immvis.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cimmvis.proto\"\x06\n\x04Void\"*\n\x16OpenDatasetFileRequest\x12\x10\n\x08\x66ilePath\x18\x01 \x01(\t\"/\n\x17OpenDatasetFileResponse\x12\x14\n\x0cresponseCode\x18\x01 \x01(\x05\"+\n\rDimensionInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t2\x83\x01\n\x06ImmVis\x12\x46\n\x0fOpenDatasetFile\x12\x17.OpenDatasetFileRequest\x1a\x18.OpenDatasetFileResponse\"\x00\x12\x31\n\x14GetDatasetDimensions\x12\x05.Void\x1a\x0e.DimensionInfo\"\x00\x30\x01\x62\x06proto3')
)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=22,
)


_OPENDATASETFILEREQUEST = _descriptor.Descriptor(
  name='OpenDatasetFileRequest',
  full_name='OpenDatasetFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filePath', full_name='OpenDatasetFileRequest.filePath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=66,
)


_OPENDATASETFILERESPONSE = _descriptor.Descriptor(
  name='OpenDatasetFileResponse',
  full_name='OpenDatasetFileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='OpenDatasetFileResponse.responseCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=115,
)


_DIMENSIONINFO = _descriptor.Descriptor(
  name='DimensionInfo',
  full_name='DimensionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DimensionInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='DimensionInfo.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=160,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['OpenDatasetFileRequest'] = _OPENDATASETFILEREQUEST
DESCRIPTOR.message_types_by_name['OpenDatasetFileResponse'] = _OPENDATASETFILERESPONSE
DESCRIPTOR.message_types_by_name['DimensionInfo'] = _DIMENSIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:Void)
  ))
_sym_db.RegisterMessage(Void)

OpenDatasetFileRequest = _reflection.GeneratedProtocolMessageType('OpenDatasetFileRequest', (_message.Message,), dict(
  DESCRIPTOR = _OPENDATASETFILEREQUEST,
  __module__ = 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:OpenDatasetFileRequest)
  ))
_sym_db.RegisterMessage(OpenDatasetFileRequest)

OpenDatasetFileResponse = _reflection.GeneratedProtocolMessageType('OpenDatasetFileResponse', (_message.Message,), dict(
  DESCRIPTOR = _OPENDATASETFILERESPONSE,
  __module__ = 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:OpenDatasetFileResponse)
  ))
_sym_db.RegisterMessage(OpenDatasetFileResponse)

DimensionInfo = _reflection.GeneratedProtocolMessageType('DimensionInfo', (_message.Message,), dict(
  DESCRIPTOR = _DIMENSIONINFO,
  __module__ = 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:DimensionInfo)
  ))
_sym_db.RegisterMessage(DimensionInfo)



_IMMVIS = _descriptor.ServiceDescriptor(
  name='ImmVis',
  full_name='ImmVis',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=163,
  serialized_end=294,
  methods=[
  _descriptor.MethodDescriptor(
    name='OpenDatasetFile',
    full_name='ImmVis.OpenDatasetFile',
    index=0,
    containing_service=None,
    input_type=_OPENDATASETFILEREQUEST,
    output_type=_OPENDATASETFILERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDatasetDimensions',
    full_name='ImmVis.GetDatasetDimensions',
    index=1,
    containing_service=None,
    input_type=_VOID,
    output_type=_DIMENSIONINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMMVIS)

DESCRIPTOR.services_by_name['ImmVis'] = _IMMVIS

# @@protoc_insertion_point(module_scope)
