# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import immvis_pb2 as immvis__pb2


class ImmVisStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.OpenDatasetFile = channel.unary_unary(
        '/ImmVis/OpenDatasetFile',
        request_serializer=immvis__pb2.OpenDatasetFileRequest.SerializeToString,
        response_deserializer=immvis__pb2.OpenDatasetFileResponse.FromString,
        )
    self.GetDatasetDimensions = channel.unary_stream(
        '/ImmVis/GetDatasetDimensions',
        request_serializer=immvis__pb2.Void.SerializeToString,
        response_deserializer=immvis__pb2.DimensionInfo.FromString,
        )
    self.GetDimensionDescriptiveStatistics = channel.unary_stream(
        '/ImmVis/GetDimensionDescriptiveStatistics',
        request_serializer=immvis__pb2.Dimension.SerializeToString,
        response_deserializer=immvis__pb2.Feature.FromString,
        )
    self.GetDimensionInfo = channel.unary_unary(
        '/ImmVis/GetDimensionInfo',
        request_serializer=immvis__pb2.Dimension.SerializeToString,
        response_deserializer=immvis__pb2.DimensionInfo.FromString,
        )
    self.GetDimensionData = channel.stream_stream(
        '/ImmVis/GetDimensionData',
        request_serializer=immvis__pb2.Dimension.SerializeToString,
        response_deserializer=immvis__pb2.DimensionData.FromString,
        )
    self.GetOutlierMapping = channel.stream_unary(
        '/ImmVis/GetOutlierMapping',
        request_serializer=immvis__pb2.Dimension.SerializeToString,
        response_deserializer=immvis__pb2.DimensionData.FromString,
        )
    self.GetKMeansCentroids = channel.unary_stream(
        '/ImmVis/GetKMeansCentroids',
        request_serializer=immvis__pb2.KMeansRequest.SerializeToString,
        response_deserializer=immvis__pb2.KMeansCentroid.FromString,
        )
    self.GetKMeansClusterMapping = channel.unary_unary(
        '/ImmVis/GetKMeansClusterMapping',
        request_serializer=immvis__pb2.KMeansRequest.SerializeToString,
        response_deserializer=immvis__pb2.DimensionData.FromString,
        )


class ImmVisServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def OpenDatasetFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDatasetDimensions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDimensionDescriptiveStatistics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDimensionInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDimensionData(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOutlierMapping(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetKMeansCentroids(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetKMeansClusterMapping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImmVisServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'OpenDatasetFile': grpc.unary_unary_rpc_method_handler(
          servicer.OpenDatasetFile,
          request_deserializer=immvis__pb2.OpenDatasetFileRequest.FromString,
          response_serializer=immvis__pb2.OpenDatasetFileResponse.SerializeToString,
      ),
      'GetDatasetDimensions': grpc.unary_stream_rpc_method_handler(
          servicer.GetDatasetDimensions,
          request_deserializer=immvis__pb2.Void.FromString,
          response_serializer=immvis__pb2.DimensionInfo.SerializeToString,
      ),
      'GetDimensionDescriptiveStatistics': grpc.unary_stream_rpc_method_handler(
          servicer.GetDimensionDescriptiveStatistics,
          request_deserializer=immvis__pb2.Dimension.FromString,
          response_serializer=immvis__pb2.Feature.SerializeToString,
      ),
      'GetDimensionInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetDimensionInfo,
          request_deserializer=immvis__pb2.Dimension.FromString,
          response_serializer=immvis__pb2.DimensionInfo.SerializeToString,
      ),
      'GetDimensionData': grpc.stream_stream_rpc_method_handler(
          servicer.GetDimensionData,
          request_deserializer=immvis__pb2.Dimension.FromString,
          response_serializer=immvis__pb2.DimensionData.SerializeToString,
      ),
      'GetOutlierMapping': grpc.stream_unary_rpc_method_handler(
          servicer.GetOutlierMapping,
          request_deserializer=immvis__pb2.Dimension.FromString,
          response_serializer=immvis__pb2.DimensionData.SerializeToString,
      ),
      'GetKMeansCentroids': grpc.unary_stream_rpc_method_handler(
          servicer.GetKMeansCentroids,
          request_deserializer=immvis__pb2.KMeansRequest.FromString,
          response_serializer=immvis__pb2.KMeansCentroid.SerializeToString,
      ),
      'GetKMeansClusterMapping': grpc.unary_unary_rpc_method_handler(
          servicer.GetKMeansClusterMapping,
          request_deserializer=immvis__pb2.KMeansRequest.FromString,
          response_serializer=immvis__pb2.DimensionData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ImmVis', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
