# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import immvis_pb2 as immvis__pb2


class ImmVisStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.OpenDatasetFile = channel.unary_unary(
        '/ImmVis/OpenDatasetFile',
        request_serializer=immvis__pb2.OpenDatasetFileRequest.SerializeToString,
        response_deserializer=immvis__pb2.OpenDatasetFileResponse.FromString,
        )
    self.GetDatasetDimensions = channel.unary_stream(
        '/ImmVis/GetDatasetDimensions',
        request_serializer=immvis__pb2.Void.SerializeToString,
        response_deserializer=immvis__pb2.DimensionInfo.FromString,
        )


class ImmVisServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def OpenDatasetFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDatasetDimensions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImmVisServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'OpenDatasetFile': grpc.unary_unary_rpc_method_handler(
          servicer.OpenDatasetFile,
          request_deserializer=immvis__pb2.OpenDatasetFileRequest.FromString,
          response_serializer=immvis__pb2.OpenDatasetFileResponse.SerializeToString,
      ),
      'GetDatasetDimensions': grpc.unary_stream_rpc_method_handler(
          servicer.GetDatasetDimensions,
          request_deserializer=immvis__pb2.Void.FromString,
          response_serializer=immvis__pb2.DimensionInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ImmVis', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
