# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import immvis_pb2 as immvis__pb2


class ImmVisStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.OpenDatasetFile = channel.unary_unary(
        '/ImmVis/OpenDatasetFile',
        request_serializer=immvis__pb2.OpenDatasetFileRequest.SerializeToString,
        response_deserializer=immvis__pb2.OpenDatasetFileResponse.FromString,
        )
    self.GetDatasetDimensions = channel.unary_stream(
        '/ImmVis/GetDatasetDimensions',
        request_serializer=immvis__pb2.Void.SerializeToString,
        response_deserializer=immvis__pb2.DimensionInfo.FromString,
        )
    self.GetDimensionFloatValues = channel.unary_stream(
        '/ImmVis/GetDimensionFloatValues',
        request_serializer=immvis__pb2.Dimension.SerializeToString,
        response_deserializer=immvis__pb2.FloatDimensionValue.FromString,
        )
    self.GetDimensionFloatHead = channel.unary_stream(
        '/ImmVis/GetDimensionFloatHead',
        request_serializer=immvis__pb2.Dimension.SerializeToString,
        response_deserializer=immvis__pb2.FloatDimensionValue.FromString,
        )
    self.GetDimensionFloatTail = channel.unary_stream(
        '/ImmVis/GetDimensionFloatTail',
        request_serializer=immvis__pb2.Dimension.SerializeToString,
        response_deserializer=immvis__pb2.FloatDimensionValue.FromString,
        )
    self.GetDimensionStringValues = channel.unary_stream(
        '/ImmVis/GetDimensionStringValues',
        request_serializer=immvis__pb2.Dimension.SerializeToString,
        response_deserializer=immvis__pb2.StringDimensionValue.FromString,
        )
    self.GetDimensionDescriptiveStatistics = channel.unary_stream(
        '/ImmVis/GetDimensionDescriptiveStatistics',
        request_serializer=immvis__pb2.Dimension.SerializeToString,
        response_deserializer=immvis__pb2.Feature.FromString,
        )


class ImmVisServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def OpenDatasetFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDatasetDimensions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDimensionFloatValues(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDimensionFloatHead(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDimensionFloatTail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDimensionStringValues(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDimensionDescriptiveStatistics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImmVisServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'OpenDatasetFile': grpc.unary_unary_rpc_method_handler(
          servicer.OpenDatasetFile,
          request_deserializer=immvis__pb2.OpenDatasetFileRequest.FromString,
          response_serializer=immvis__pb2.OpenDatasetFileResponse.SerializeToString,
      ),
      'GetDatasetDimensions': grpc.unary_stream_rpc_method_handler(
          servicer.GetDatasetDimensions,
          request_deserializer=immvis__pb2.Void.FromString,
          response_serializer=immvis__pb2.DimensionInfo.SerializeToString,
      ),
      'GetDimensionFloatValues': grpc.unary_stream_rpc_method_handler(
          servicer.GetDimensionFloatValues,
          request_deserializer=immvis__pb2.Dimension.FromString,
          response_serializer=immvis__pb2.FloatDimensionValue.SerializeToString,
      ),
      'GetDimensionFloatHead': grpc.unary_stream_rpc_method_handler(
          servicer.GetDimensionFloatHead,
          request_deserializer=immvis__pb2.Dimension.FromString,
          response_serializer=immvis__pb2.FloatDimensionValue.SerializeToString,
      ),
      'GetDimensionFloatTail': grpc.unary_stream_rpc_method_handler(
          servicer.GetDimensionFloatTail,
          request_deserializer=immvis__pb2.Dimension.FromString,
          response_serializer=immvis__pb2.FloatDimensionValue.SerializeToString,
      ),
      'GetDimensionStringValues': grpc.unary_stream_rpc_method_handler(
          servicer.GetDimensionStringValues,
          request_deserializer=immvis__pb2.Dimension.FromString,
          response_serializer=immvis__pb2.StringDimensionValue.SerializeToString,
      ),
      'GetDimensionDescriptiveStatistics': grpc.unary_stream_rpc_method_handler(
          servicer.GetDimensionDescriptiveStatistics,
          request_deserializer=immvis__pb2.Dimension.FromString,
          response_serializer=immvis__pb2.Feature.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ImmVis', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
