# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: immvis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='immvis.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cimmvis.proto\x1a\x1bgoogle/protobuf/empty.proto\".\n\x15\x41vailableDatasetsList\x12\x15\n\rdatasetsPaths\x18\x01 \x03(\t\"0\n\x19LoadDatasetRequestMessage\x12\x13\n\x0b\x64\x61tasetPath\x18\x01 \x01(\t\"*\n\x06\x43olumn\x12\x12\n\ncolumnName\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"I\n\x1c\x44\x65scriptiveStatisticsFeature\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\"|\n\x1b\x43olumnDescriptiveStatistics\x12\x17\n\x06\x63olumn\x18\x01 \x01(\x0b\x32\x07.Column\x12\x44\n\x1d\x64\x65scriptiveStatisticsFeatures\x18\x02 \x03(\x0b\x32\x1d.DescriptiveStatisticsFeature\"\x82\x01\n\x0f\x44\x61tasetMetadata\x12\x11\n\trowsCount\x18\x01 \x01(\x05\x12\x18\n\x07\x63olumns\x18\x02 \x03(\x0b\x32\x07.Column\x12\x42\n\x1c\x63olumnsDescriptiveStatistics\x18\x03 \x03(\x0b\x32\x1c.ColumnDescriptiveStatistics2\x92\x01\n\x06ImmVis\x12I\n\x15ListAvailableDatasets\x12\x16.google.protobuf.Empty\x1a\x16.AvailableDatasetsList\"\x00\x12=\n\x0bLoadDataset\x12\x1a.LoadDatasetRequestMessage\x1a\x10.DatasetMetadata\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_AVAILABLEDATASETSLIST = _descriptor.Descriptor(
  name='AvailableDatasetsList',
  full_name='AvailableDatasetsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datasetsPaths', full_name='AvailableDatasetsList.datasetsPaths', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=91,
)


_LOADDATASETREQUESTMESSAGE = _descriptor.Descriptor(
  name='LoadDatasetRequestMessage',
  full_name='LoadDatasetRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datasetPath', full_name='LoadDatasetRequestMessage.datasetPath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=141,
)


_COLUMN = _descriptor.Descriptor(
  name='Column',
  full_name='Column',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='columnName', full_name='Column.columnName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='Column.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=185,
)


_DESCRIPTIVESTATISTICSFEATURE = _descriptor.Descriptor(
  name='DescriptiveStatisticsFeature',
  full_name='DescriptiveStatisticsFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DescriptiveStatisticsFeature.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='DescriptiveStatisticsFeature.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='DescriptiveStatisticsFeature.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=260,
)


_COLUMNDESCRIPTIVESTATISTICS = _descriptor.Descriptor(
  name='ColumnDescriptiveStatistics',
  full_name='ColumnDescriptiveStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='column', full_name='ColumnDescriptiveStatistics.column', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='descriptiveStatisticsFeatures', full_name='ColumnDescriptiveStatistics.descriptiveStatisticsFeatures', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=386,
)


_DATASETMETADATA = _descriptor.Descriptor(
  name='DatasetMetadata',
  full_name='DatasetMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rowsCount', full_name='DatasetMetadata.rowsCount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='columns', full_name='DatasetMetadata.columns', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='columnsDescriptiveStatistics', full_name='DatasetMetadata.columnsDescriptiveStatistics', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=519,
)

_COLUMNDESCRIPTIVESTATISTICS.fields_by_name['column'].message_type = _COLUMN
_COLUMNDESCRIPTIVESTATISTICS.fields_by_name['descriptiveStatisticsFeatures'].message_type = _DESCRIPTIVESTATISTICSFEATURE
_DATASETMETADATA.fields_by_name['columns'].message_type = _COLUMN
_DATASETMETADATA.fields_by_name['columnsDescriptiveStatistics'].message_type = _COLUMNDESCRIPTIVESTATISTICS
DESCRIPTOR.message_types_by_name['AvailableDatasetsList'] = _AVAILABLEDATASETSLIST
DESCRIPTOR.message_types_by_name['LoadDatasetRequestMessage'] = _LOADDATASETREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['Column'] = _COLUMN
DESCRIPTOR.message_types_by_name['DescriptiveStatisticsFeature'] = _DESCRIPTIVESTATISTICSFEATURE
DESCRIPTOR.message_types_by_name['ColumnDescriptiveStatistics'] = _COLUMNDESCRIPTIVESTATISTICS
DESCRIPTOR.message_types_by_name['DatasetMetadata'] = _DATASETMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AvailableDatasetsList = _reflection.GeneratedProtocolMessageType('AvailableDatasetsList', (_message.Message,), {
  'DESCRIPTOR' : _AVAILABLEDATASETSLIST,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:AvailableDatasetsList)
  })
_sym_db.RegisterMessage(AvailableDatasetsList)

LoadDatasetRequestMessage = _reflection.GeneratedProtocolMessageType('LoadDatasetRequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOADDATASETREQUESTMESSAGE,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:LoadDatasetRequestMessage)
  })
_sym_db.RegisterMessage(LoadDatasetRequestMessage)

Column = _reflection.GeneratedProtocolMessageType('Column', (_message.Message,), {
  'DESCRIPTOR' : _COLUMN,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:Column)
  })
_sym_db.RegisterMessage(Column)

DescriptiveStatisticsFeature = _reflection.GeneratedProtocolMessageType('DescriptiveStatisticsFeature', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIPTIVESTATISTICSFEATURE,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:DescriptiveStatisticsFeature)
  })
_sym_db.RegisterMessage(DescriptiveStatisticsFeature)

ColumnDescriptiveStatistics = _reflection.GeneratedProtocolMessageType('ColumnDescriptiveStatistics', (_message.Message,), {
  'DESCRIPTOR' : _COLUMNDESCRIPTIVESTATISTICS,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:ColumnDescriptiveStatistics)
  })
_sym_db.RegisterMessage(ColumnDescriptiveStatistics)

DatasetMetadata = _reflection.GeneratedProtocolMessageType('DatasetMetadata', (_message.Message,), {
  'DESCRIPTOR' : _DATASETMETADATA,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:DatasetMetadata)
  })
_sym_db.RegisterMessage(DatasetMetadata)



_IMMVIS = _descriptor.ServiceDescriptor(
  name='ImmVis',
  full_name='ImmVis',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=522,
  serialized_end=668,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListAvailableDatasets',
    full_name='ImmVis.ListAvailableDatasets',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_AVAILABLEDATASETSLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LoadDataset',
    full_name='ImmVis.LoadDataset',
    index=1,
    containing_service=None,
    input_type=_LOADDATASETREQUESTMESSAGE,
    output_type=_DATASETMETADATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMMVIS)

DESCRIPTOR.services_by_name['ImmVis'] = _IMMVIS

# @@protoc_insertion_point(module_scope)
