# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import immvis_pb2 as immvis__pb2


class ImmVisPandasStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListAvailableDatasets = channel.unary_unary(
        '/ImmVisPandas/ListAvailableDatasets',
        request_serializer=immvis__pb2.Empty.SerializeToString,
        response_deserializer=immvis__pb2.AvailableDatasetsList.FromString,
        )
    self.LoadDataset = channel.unary_unary(
        '/ImmVisPandas/LoadDataset',
        request_serializer=immvis__pb2.LoadDatasetRequest.SerializeToString,
        response_deserializer=immvis__pb2.DatasetMetadata.FromString,
        )
    self.GetNormalisedDataset = channel.unary_unary(
        '/ImmVisPandas/GetNormalisedDataset',
        request_serializer=immvis__pb2.GetNormalisedDatasetRequest.SerializeToString,
        response_deserializer=immvis__pb2.NormalisedDataset.FromString,
        )
    self.GenerateDataset = channel.unary_unary(
        '/ImmVisPandas/GenerateDataset',
        request_serializer=immvis__pb2.GenerateDatasetRequest.SerializeToString,
        response_deserializer=immvis__pb2.DatasetMetadata.FromString,
        )
    self.DoKMeansAnalysis = channel.unary_unary(
        '/ImmVisPandas/DoKMeansAnalysis',
        request_serializer=immvis__pb2.KMeansAnalysisRequest.SerializeToString,
        response_deserializer=immvis__pb2.KMeansAnalysisResponse.FromString,
        )


class ImmVisPandasServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListAvailableDatasets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoadDataset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNormalisedDataset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenerateDataset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DoKMeansAnalysis(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImmVisPandasServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListAvailableDatasets': grpc.unary_unary_rpc_method_handler(
          servicer.ListAvailableDatasets,
          request_deserializer=immvis__pb2.Empty.FromString,
          response_serializer=immvis__pb2.AvailableDatasetsList.SerializeToString,
      ),
      'LoadDataset': grpc.unary_unary_rpc_method_handler(
          servicer.LoadDataset,
          request_deserializer=immvis__pb2.LoadDatasetRequest.FromString,
          response_serializer=immvis__pb2.DatasetMetadata.SerializeToString,
      ),
      'GetNormalisedDataset': grpc.unary_unary_rpc_method_handler(
          servicer.GetNormalisedDataset,
          request_deserializer=immvis__pb2.GetNormalisedDatasetRequest.FromString,
          response_serializer=immvis__pb2.NormalisedDataset.SerializeToString,
      ),
      'GenerateDataset': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateDataset,
          request_deserializer=immvis__pb2.GenerateDatasetRequest.FromString,
          response_serializer=immvis__pb2.DatasetMetadata.SerializeToString,
      ),
      'DoKMeansAnalysis': grpc.unary_unary_rpc_method_handler(
          servicer.DoKMeansAnalysis,
          request_deserializer=immvis__pb2.KMeansAnalysisRequest.FromString,
          response_serializer=immvis__pb2.KMeansAnalysisResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ImmVisPandas', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
