# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: immvis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='immvis.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cimmvis.proto\"\x07\n\x05\x45mpty\".\n\x15\x41vailableDatasetsList\x12\x15\n\rdatasetsPaths\x18\x01 \x03(\t\"0\n\x19LoadDatasetRequestMessage\x12\x13\n\x0b\x64\x61tasetPath\x18\x01 \x01(\t\"*\n\x06\x43olumn\x12\x12\n\ncolumnName\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"P\n\x1c\x44\x65scriptiveStatisticsFeature\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x13\n\x0b\x66\x65\x61tureType\x18\x03 \x01(\t\"k\n\nColumnInfo\x12\x17\n\x06\x63olumn\x18\x01 \x01(\x0b\x32\x07.Column\x12\x44\n\x1d\x64\x65scriptiveStatisticsFeatures\x18\x02 \x03(\x0b\x32\x1d.DescriptiveStatisticsFeature\"\\\n\x0f\x44\x61tasetMetadata\x12\x11\n\trowsCount\x18\x01 \x01(\x05\x12\x14\n\x0c\x63olumnsCount\x18\x02 \x01(\x05\x12 \n\x0b\x63olumnsInfo\x18\x03 \x03(\x0b\x32\x0b.ColumnInfo\"6\n\x1eGetDatasetToPlotRequestMessage\x12\x14\n\x0c\x63olumnsNames\x18\x01 \x03(\t\"*\n\rDatasetToPlot\x12\x19\n\x04rows\x18\x01 \x03(\x0b\x32\x0b.DatasetRow\"\x1f\n\nDatasetRow\x12\x11\n\trowValues\x18\x01 \x03(\x02\x32\xcf\x01\n\x0cImmVisPandas\x12\x39\n\x15ListAvailableDatasets\x12\x06.Empty\x1a\x16.AvailableDatasetsList\"\x00\x12=\n\x0bLoadDataset\x12\x1a.LoadDatasetRequestMessage\x1a\x10.DatasetMetadata\"\x00\x12\x45\n\x10GetDatasetToPlot\x12\x1f.GetDatasetToPlotRequestMessage\x1a\x0e.DatasetToPlot\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=23,
)


_AVAILABLEDATASETSLIST = _descriptor.Descriptor(
  name='AvailableDatasetsList',
  full_name='AvailableDatasetsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datasetsPaths', full_name='AvailableDatasetsList.datasetsPaths', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=71,
)


_LOADDATASETREQUESTMESSAGE = _descriptor.Descriptor(
  name='LoadDatasetRequestMessage',
  full_name='LoadDatasetRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datasetPath', full_name='LoadDatasetRequestMessage.datasetPath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=121,
)


_COLUMN = _descriptor.Descriptor(
  name='Column',
  full_name='Column',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='columnName', full_name='Column.columnName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='Column.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=165,
)


_DESCRIPTIVESTATISTICSFEATURE = _descriptor.Descriptor(
  name='DescriptiveStatisticsFeature',
  full_name='DescriptiveStatisticsFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DescriptiveStatisticsFeature.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='DescriptiveStatisticsFeature.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='featureType', full_name='DescriptiveStatisticsFeature.featureType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=247,
)


_COLUMNINFO = _descriptor.Descriptor(
  name='ColumnInfo',
  full_name='ColumnInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='column', full_name='ColumnInfo.column', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='descriptiveStatisticsFeatures', full_name='ColumnInfo.descriptiveStatisticsFeatures', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=356,
)


_DATASETMETADATA = _descriptor.Descriptor(
  name='DatasetMetadata',
  full_name='DatasetMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rowsCount', full_name='DatasetMetadata.rowsCount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='columnsCount', full_name='DatasetMetadata.columnsCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='columnsInfo', full_name='DatasetMetadata.columnsInfo', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=450,
)


_GETDATASETTOPLOTREQUESTMESSAGE = _descriptor.Descriptor(
  name='GetDatasetToPlotRequestMessage',
  full_name='GetDatasetToPlotRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='columnsNames', full_name='GetDatasetToPlotRequestMessage.columnsNames', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=506,
)


_DATASETTOPLOT = _descriptor.Descriptor(
  name='DatasetToPlot',
  full_name='DatasetToPlot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='DatasetToPlot.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=550,
)


_DATASETROW = _descriptor.Descriptor(
  name='DatasetRow',
  full_name='DatasetRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rowValues', full_name='DatasetRow.rowValues', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=583,
)

_COLUMNINFO.fields_by_name['column'].message_type = _COLUMN
_COLUMNINFO.fields_by_name['descriptiveStatisticsFeatures'].message_type = _DESCRIPTIVESTATISTICSFEATURE
_DATASETMETADATA.fields_by_name['columnsInfo'].message_type = _COLUMNINFO
_DATASETTOPLOT.fields_by_name['rows'].message_type = _DATASETROW
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['AvailableDatasetsList'] = _AVAILABLEDATASETSLIST
DESCRIPTOR.message_types_by_name['LoadDatasetRequestMessage'] = _LOADDATASETREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['Column'] = _COLUMN
DESCRIPTOR.message_types_by_name['DescriptiveStatisticsFeature'] = _DESCRIPTIVESTATISTICSFEATURE
DESCRIPTOR.message_types_by_name['ColumnInfo'] = _COLUMNINFO
DESCRIPTOR.message_types_by_name['DatasetMetadata'] = _DATASETMETADATA
DESCRIPTOR.message_types_by_name['GetDatasetToPlotRequestMessage'] = _GETDATASETTOPLOTREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['DatasetToPlot'] = _DATASETTOPLOT
DESCRIPTOR.message_types_by_name['DatasetRow'] = _DATASETROW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

AvailableDatasetsList = _reflection.GeneratedProtocolMessageType('AvailableDatasetsList', (_message.Message,), {
  'DESCRIPTOR' : _AVAILABLEDATASETSLIST,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:AvailableDatasetsList)
  })
_sym_db.RegisterMessage(AvailableDatasetsList)

LoadDatasetRequestMessage = _reflection.GeneratedProtocolMessageType('LoadDatasetRequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOADDATASETREQUESTMESSAGE,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:LoadDatasetRequestMessage)
  })
_sym_db.RegisterMessage(LoadDatasetRequestMessage)

Column = _reflection.GeneratedProtocolMessageType('Column', (_message.Message,), {
  'DESCRIPTOR' : _COLUMN,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:Column)
  })
_sym_db.RegisterMessage(Column)

DescriptiveStatisticsFeature = _reflection.GeneratedProtocolMessageType('DescriptiveStatisticsFeature', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIPTIVESTATISTICSFEATURE,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:DescriptiveStatisticsFeature)
  })
_sym_db.RegisterMessage(DescriptiveStatisticsFeature)

ColumnInfo = _reflection.GeneratedProtocolMessageType('ColumnInfo', (_message.Message,), {
  'DESCRIPTOR' : _COLUMNINFO,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:ColumnInfo)
  })
_sym_db.RegisterMessage(ColumnInfo)

DatasetMetadata = _reflection.GeneratedProtocolMessageType('DatasetMetadata', (_message.Message,), {
  'DESCRIPTOR' : _DATASETMETADATA,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:DatasetMetadata)
  })
_sym_db.RegisterMessage(DatasetMetadata)

GetDatasetToPlotRequestMessage = _reflection.GeneratedProtocolMessageType('GetDatasetToPlotRequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _GETDATASETTOPLOTREQUESTMESSAGE,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:GetDatasetToPlotRequestMessage)
  })
_sym_db.RegisterMessage(GetDatasetToPlotRequestMessage)

DatasetToPlot = _reflection.GeneratedProtocolMessageType('DatasetToPlot', (_message.Message,), {
  'DESCRIPTOR' : _DATASETTOPLOT,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:DatasetToPlot)
  })
_sym_db.RegisterMessage(DatasetToPlot)

DatasetRow = _reflection.GeneratedProtocolMessageType('DatasetRow', (_message.Message,), {
  'DESCRIPTOR' : _DATASETROW,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:DatasetRow)
  })
_sym_db.RegisterMessage(DatasetRow)



_IMMVISPANDAS = _descriptor.ServiceDescriptor(
  name='ImmVisPandas',
  full_name='ImmVisPandas',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=586,
  serialized_end=793,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListAvailableDatasets',
    full_name='ImmVisPandas.ListAvailableDatasets',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_AVAILABLEDATASETSLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LoadDataset',
    full_name='ImmVisPandas.LoadDataset',
    index=1,
    containing_service=None,
    input_type=_LOADDATASETREQUESTMESSAGE,
    output_type=_DATASETMETADATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDatasetToPlot',
    full_name='ImmVisPandas.GetDatasetToPlot',
    index=2,
    containing_service=None,
    input_type=_GETDATASETTOPLOTREQUESTMESSAGE,
    output_type=_DATASETTOPLOT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMMVISPANDAS)

DESCRIPTOR.services_by_name['ImmVisPandas'] = _IMMVISPANDAS

# @@protoc_insertion_point(module_scope)
